# GitLab CI/CD: build and push image; optional deploy
# Set CI/CD variables in GitLab: JIRA_*, GROQ_*, etc. (or use your deploy env)

stages:
  - build
  # - deploy   # uncomment and add your deploy job

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE -t $CI_REGISTRY_IMAGE:latest .
    - docker push $DOCKER_IMAGE
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

# Example deploy job (customize for your cluster/server):
# deploy:
#   stage: deploy
#   image: alpine/k8s:1.28.2
#   script:
#     - kubectl set image deployment/jira-team-utility app=$DOCKER_IMAGE -n your-namespace
#   only:
#     - master
